export default class BlockLists {

    public static readonly item0List = new Map<string, number | null>([
        ["minecraft:grass", null],
        ["minecraft:dirt", null],
        ["minecraft:log", null],
        ["minecraft:log", 1],
        ["minecraft:log", 2],
        ["minecraft:log", 3]
    ]);
    public static readonly item50List = new Map<string, number | null>([
        ["minecraft:log2", null],
        ["minecraft:log2", 1],
        ["minecraft:cherry_log", null],
        ["minecraft:melon_block", null],
        ["minecraft:pumpkin", null]
    ]);
    public static readonly item250List = new Map<string, number | null>([
        ["minecraft:cobblestone", null],
        ["minecraft:gravel", null],
        ["minecraft:sand", null],
        ["minecraft:coal_ore", null],
        ["minecraft:leaves", null],
        ["minecraft:leaves", 1],
        ["minecraft:leaves", 2],
        ["minecraft:leaves", 3],
        ["minecraft:leaves2", null],
        ["minecraft:leaves2", 1],
        ["minecraft:azalea_leaves", 1],
        ["minecraft:flowering_azalea_leaves", 1]
    ]);
    public static readonly item500List = new Map<string, number | null>([
        ["minecraft:stone", null],
        ["minecraft:stone", 1],
        ["minecraft:stone", 3],
        ["minecraft:stone", 5],
        ["minecraft:stone", null],
        ["minecraft:copper_ore", null],
        ["minecraft:iron_ore", null],
        ["minecraft:clay", null],
        ["minecraft:hay_bale", null]
    ]);
    public static readonly item1200List = new Map<string, number | null>([
        ["minecraft:sand", 1],
        ["minecraft:gold_ore", null],
        ["minecraft:wool", null],
        ["minecraft:moss_block", null],
        ["minecraft:bamboo_block", null],
        ["minecraft:cactus", null]
    ]);
    public static readonly item2400List = new Map<string, number | null>([
        ["minecraft:stone", 2],
        ["minecraft:stone", 4],
        ["minecraft:stone", 6],
        ["minecraft:dirt", 1],
        ["minecraft:dirt", 2],
        ["minecraft:lapis_ore", null],
        ["minecraft:redstone_ore", null],
        ["minecraft:snow", null],
        ["minecraft:emerald_ore", null],
        ["minecraft:quartz", null],
        ["minecraft:hardened_clay", null],
        ["minecraft:prismarine", null],
        ["minecraft:prismarine", 1],
        ["minecraft:prismarine", 2],
        ["minecraft:sea_lantern", null],
        ["minecraft:ice", null],
        ["minecraft:packed_ice", null],
        ["minecraft:blue_ice", null]
    ]);
    public static readonly item3000List = new Map<string, number | null>([
        ["minecraft:glass", null],
        ["minecraft:wool", null],
        ["minecraft:wool", 1],
        ["minecraft:wool", 2],
        ["minecraft:wool", 3],
        ["minecraft:wool", 4],
        ["minecraft:wool", 5],
        ["minecraft:wool", 6],
        ["minecraft:wool", 7],
        ["minecraft:wool", 8],
        ["minecraft:wool", 9],
        ["minecraft:wool", 10],
        ["minecraft:wool", 11],
        ["minecraft:wool", 12],
        ["minecraft:wool", 13],
        ["minecraft:wool", 14],
        ["minecraft:wool", 15],
        ["minecraft:diamond_ore", null],
        ["minecraft:stained_glass", null],
        ["minecraft:stained_glass", 1],
        ["minecraft:stained_glass", 2],
        ["minecraft:stained_glass", 3],
        ["minecraft:stained_glass", 4],
        ["minecraft:stained_glass", 5],
        ["minecraft:stained_glass", 6],
        ["minecraft:stained_glass", 7],
        ["minecraft:stained_glass", 8],
        ["minecraft:stained_glass", 9],
        ["minecraft:stained_glass", 10],
        ["minecraft:stained_glass", 11],
        ["minecraft:stained_glass", 12],
        ["minecraft:stained_glass", 13],
        ["minecraft:stained_glass", 14],
        ["minecraft:stained_glass", 15],
        ["minecraft:cobbled_deepslate", null],
        ["minecraft:deepslate_coal_ore", null],
        ["minecraft:deepslate_copper_ore", null],
        ["minecraft:deepslate_diamond_ore", null],
        ["minecraft:deepslate_emerald_ore", null],
        ["minecraft:deepslate_gold_ore", null],
        ["minecraft:deepslate_iron_ore", null],
        ["minecraft:deepslate_lapis_ore", null],
        ["minecraft:deepslate_redstone_ore", null],
        ["minecraft:deepslate", null],
        ["minecraft:dripstone_block", null],
        ["minecraft:tinted_glass", null],
        ["minecraft:deepslate_tiles", null]
    ]);
    public static readonly item3600List = new Map<string, number | null>([
        ["minecraft:coal_block", null],
        ["minecraft:brick_block", null],
        ["minecraft:glowstone", null],
        ["minecraft:stained_hardened_clay", null],
        ["minecraft:stained_hardened_clay", 1],
        ["minecraft:stained_hardened_clay", 2],
        ["minecraft:stained_hardened_clay", 3],
        ["minecraft:stained_hardened_clay", 4],
        ["minecraft:stained_hardened_clay", 5],
        ["minecraft:stained_hardened_clay", 6],
        ["minecraft:stained_hardened_clay", 7],
        ["minecraft:stained_hardened_clay", 8],
        ["minecraft:stained_hardened_clay", 9],
        ["minecraft:stained_hardened_clay", 10],
        ["minecraft:stained_hardened_clay", 11],
        ["minecraft:stained_hardened_clay", 12],
        ["minecraft:stained_hardened_clay", 13],
        ["minecraft:stained_hardened_clay", 14],
        ["minecraft:stained_hardened_clay", 15],
        ["minecraft:hardened_clay", null],
        ["minecraft:obsidian", null],
        ["minecraft:amethyst_block", null],
        ["minecraft:budding_amethyst", null],
        ["minecraft:calcite", null],
        ["minecraft:tuff", null]
    ]);
    public static readonly item4700List = new Map<string, number | null>([
        ["minecraft:nether_brick", null],
        ["minecraft:magma", null],
        ["minecraft:nether_wart_block", null],
        ["minecraft:red_nether_brick", null],
        ["minecraft:white_glazed_terracotta", null],
        ["minecraft:orange_glazed_terracotta", null],
        ["minecraft:magenta_glazed_terracotta", null],
        ["minecraft:light_blue_glazed_terracotta", null],
        ["minecraft:yellow_glazed_terracotta", null],
        ["minecraft:lime_glazed_terracotta", null],
        ["minecraft:pink_glazed_terracotta", null],
        ["minecraft:gray_glazed_terracotta", null],
        ["minecraft:light_gray_glazed_terracotta", null],
        ["minecraft:cyan_glazed_terracotta", null],
        ["minecraft:purple_glazed_terracotta", null],
        ["minecraft:blue_glazed_terracotta", null],
        ["minecraft:brown_glazed_terracotta", null],
        ["minecraft:green_glazed_terracotta", null],
        ["minecraft:red_glazed_terracotta", null],
        ["minecraft:black_glazed_terracotta", null],
        ["minecraft:crimson_nylium", null],
        ["minecraft:warped_nylium", null],
        ["minecraft:nether_gold_ore", null],
        ["minecraft:crimson_stem", null],
        ["minecraft:warped_stem", null],
        ["minecraft:soul_soil", null],
        ["minecraft:basalt", null],
        ["minecraft:shroomlight", null],
        ["minecraft:ancient_debris", null],
        ["minecraft:soul_sand", null],
        ["minecraft:quartz_ore", null],
        ["minecraft:polished_basalt", null],
        ["minecraft:smooth_basalt", null]
    ]);
    public static readonly item5300List = new Map<string, number | null>([
        ["minecraft:concrete", null],
        ["minecraft:concrete", 1],
        ["minecraft:concrete", 2],
        ["minecraft:concrete", 3],
        ["minecraft:concrete", 4],
        ["minecraft:concrete", 5],
        ["minecraft:concrete", 6],
        ["minecraft:concrete", 7],
        ["minecraft:concrete", 8],
        ["minecraft:concrete", 9],
        ["minecraft:concrete", 10],
        ["minecraft:concrete", 11],
        ["minecraft:concrete", 12],
        ["minecraft:concrete", 13],
        ["minecraft:concrete", 14],
        ["minecraft:concrete", 15],
        ["minecraft:concrete_powder", null],
        ["minecraft:concrete_powder", 1],
        ["minecraft:concrete_powder", 2],
        ["minecraft:concrete_powder", 3],
        ["minecraft:concrete_powder", 4],
        ["minecraft:concrete_powder", 5],
        ["minecraft:concrete_powder", 6],
        ["minecraft:concrete_powder", 7],
        ["minecraft:concrete_powder", 8],
        ["minecraft:concrete_powder", 9],
        ["minecraft:concrete_powder", 10],
        ["minecraft:concrete_powder", 11],
        ["minecraft:concrete_powder", 12],
        ["minecraft:concrete_powder", 13],
        ["minecraft:concrete_powder", 14],
        ["minecraft:concrete_powder", 15],
        ["minecraft:tube_coral_block", null],
        ["minecraft:brain_coral_block", null],
        ["minecraft:bubble_coral_block", null],
        ["minecraft:fire_coral_block", null],
        ["minecraft:horn_coral_block", null],
        ["minecraft:tube_coral", null],
        ["minecraft:brain_coral", null],
        ["minecraft:bubble_coral", null],
        ["minecraft:fire_coral", null],
        ["minecraft:horn_coral", null],
        ["minecraft:tube_coral_fan", null],
        ["minecraft:brain_coral_fan", null],
        ["minecraft:bubble_coral_fan", null],
        ["minecraft:fire_coral_fan", null],
        ["minecraft:horn_coral_fan", null],
        ["minecraft:tube_coral_wall_fan", null],
        ["minecraft:brain_coral_wall_fan", null],
        ["minecraft:bubble_coral_wall_fan", null],
        ["minecraft:fire_coral_wall_fan", null],
        ["minecraft:horn_coral_wall_fan", null],
        ["minecraft:blackstone", null],
        ["minecraft:gilded_blackstone", null]
    ]);
    public static readonly item6666List = new Map<string, number | null>([
        ["minecraft:end_stone", null],
        ["minecraft:end_bricks", null],
        ["minecraft:purpur_block", null]
    ]);

}
